# Generated by Django 2.1.7 on 2019-04-14 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_no', models.CharField(max_length=200)),
                ('cordinates', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='templates',
            name='cordinates',
        ),
        migrations.AddField(
            model_name='blanks',
            name='templates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.Templates'),
        ),
    ]
