# Generated by Django 2.1.7 on 2019-04-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_auto_20190414_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blanks',
            old_name='cordinates',
            new_name='end',
        ),
        migrations.AddField(
            model_name='blanks',
            name='start',
            field=models.CharField(default='(0,0)', max_length=200),
            preserve_default=False,
        ),
    ]
