# Generated by Django 2.1.7 on 2019-04-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='template',
        ),
        migrations.AddField(
            model_name='csv',
            name='documentFilename',
            field=models.CharField(default='csvdefault', max_length=200),
            preserve_default=False,
        ),
    ]
