# Generated by Django 2.1.7 on 2019-04-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_remove_csv_documentfilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='title',
            field=models.CharField(default='mytemplate', max_length=200),
            preserve_default=False,
        ),
    ]
