# Generated by Django 2.1.7 on 2019-04-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0007_templates_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blanks',
            unique_together={('templates', 'blank_no')},
        ),
    ]
