# Generated by Django 2.1.7 on 2019-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0009_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='template_title',
            field=models.CharField(default='mytemplate', max_length=200),
            preserve_default=False,
        ),
    ]
